### ISSUE TITLE
Form : display inputs + labels

### ISSUE THREAD

**Issue by al2b** [Elao/accesseo#31]
For each input in form, display : 
- [x] input name
- [x] label (or missing label)

**Where ?** 

Form section (accessibility panel)

** How to test **
```<form action="" method="get" class="form-example">
  <div class="form-example">
    <label for="name">Enter your name: </label>
    <input type="text" name="name" id="name" required>
  </div>
  <div class="form-example">
   <input type="email" name="email" id="email" required>
  </div>
  <div class="form-example">
    <input type="submit" value="Subscribe!">
  </div>
</form>
```

Display : 
Input : "Name" - label : "name"
Input : "email" - missing label

**Comment by ameliedefrance** [comment]
Proposition, afficher : 
- [ ] input type
- [ ] input name
- [ ] input label
