### ISSUE TITLE
Headings warnings

### ISSUE THREAD

**Issue by ameliedefrance** [Elao/accesseo#41]
Proposition :

![Capture d’écran 2021-07-19 à 09 46 47](https://user-images.githubusercontent.com/25897625/126122496-1e7d096e-cfa6-404b-96e0-fb6cf66ca582.png)

- [x] Si pas de h1, afficher seulement l'erreur (cadre rouge)
- [ ] Si plusieurs h1, idem
- [x] Si des niveaux de titre sont dans le désordre, afficher l'erreur + signaler les titres auxquels il manque 1 parent

**Comment by al2b** [comment]
Avec HTML5, on peut avoir plusieurs titres H1 dans la page : la règle du h1 unique n'existe plus
