### ISSUE TITLE
[Composer] Could not find a version of package elao/accesseo

### ISSUE THREAD

**Issue by vinceAmstoutz** [Elao/accesseo#99]
According to the doc, when I run `composer require --dev elao/accesseo`

I have :

` [InvalidArgumentException]
  Could not find a version of package elao/accesseo matching your minimum-stability (stable). Require it with an explicit version const   
  raint allowing its desired stability.    `
  
  I have already test with the edition of the composer.json.

**Comment by al2b** [comment]
Thank you @ogizanagi !
